### ISSUE TITLE
listing dataset doesn't work anymore with gitea

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/intranet.neuro.polymtl.ca#123]
~~~
julien-macbook:~/data.neuro $ ssh git@data.neuro.polymtl.ca info

Gitea: Too few arguments
~~~

related to #117 and https://github.com/neuropoly/data-management/issues/310 https://github.com/neuropoly/computers/issues/683

**Comment by mguaypaq** [comment]
With the new instructions posted at #124, you should be able to view all the datasets from the web interface. If you specifically want to get the list from the command-line, there [`tea`, the official Gitea CLI](https://about.gitea.com/products/tea/), but I haven't tried it yet.
