### ISSUE TITLE
List all twitter accounts

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/intranet.neuro.polymtl.ca#13]
I think it would be interesting to have a list of links with all Twitter accounts for various software projects.

@jcohenadad @kousu @ahill187 What is you opinion ?

**Comment by jcohenadad** [comment]
not a list of links but rather putting the link where the project is mentioned

**Comment by kousu** [comment]
From my perspective, this is important as part of https://github.com/neuropoly/onboarding/issues/2. There are really two entwined projects there: auditing all the credentials we have, and making sure the right people have access to them.

Making a list of lab-owned twitter accounts if a by-product of that. https://github.com/neuropoly/onboarding/issues/24

**Comment by RignonNoel** [comment]
Reviewed the ticket with @jcohenadad  and @kousu. Seems to be a duplicata of https://github.com/neuropoly/neuro.polymtl.ca/issues/53.

I close this issue
