### ISSUE TITLE
cannot find easily the info to update the git annex local repository

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/intranet.neuro.polymtl.ca#29]
https://intranet.neuro.polymtl.ca/computing-resources/neuropoly/data/git-annex.html#checking-annex-file-locations

**Comment by kousu** [comment]
Are you looking for

```
git pull && git annex sync --no-content && git annex get .
```

This is documented in https://github.com/spine-generic/data-multi-subject/#download but embarrassingly I forgot the `git annex sync` step (pretty important, oops; maybe it used to say `git annex sync --content`?), and it isn't anywhere on the more general doc.

I think this should probably go in between these two sections:

![2021-11-30-153620_208x97_scrot](https://user-images.githubusercontent.com/987487/144124065-614c8cf8-685f-4a5b-a0e4-0ea74e7ae95a.png)

**Comment by jcohenadad** [comment]
Thank you @kousu i was indeed looking for this-- but then i realized that all the git-annex doc is also under the data section: https://intranet.neuro.polymtl.ca/computing-resources/neuropoly/data/git-datasets.html

so we should probably move the git-annex section somewhere else
