### ISSUE TITLE
Document Windows VPN app

### ISSUE THREAD

**Issue by kousu** [neuropoly/intranet.neuro.polymtl.ca#40]
https://intranet.neuro.polymtl.ca/computing-resources/neuropoly/README.html#vpn only covers macOS and Linux (which it mislabels PC/Linux), recommending `openconnect`. But `openconnect` doesn't run on Windows, and it misled @charleygros today into trying to run it _inside WSL_ which does not work:

```
charleygros@DOM-IMA-9RM5L13:/mnt/c/Users/cgros$ ./vpn.sh
POST https://ssl.vpn.polymtl.ca/
Connected to 132.207.3.6:443
SSL negotiation with ssl.vpn.polymtl.ca
Connected to HTTPS on ssl.vpn.polymtl.ca
XML POST enabled
POST https://ssl.vpn.polymtl.ca/
XML POST enabled
POST https://ssl.vpn.polymtl.ca/
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connected as 10.10.42.162, using SSL, with DTLS in progress
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS1.2)-(ECDHE-RSA)-(AES-256-GCM).
Failed to open tun device: No such device
Set up tun device failed
Unknown error; exiting.
```

Please document the vetted way to use the VPN from Windows.

(originally reported at https://github.com/neuropoly/computers/issues/269)

**Comment by kousu** [comment]
I think this means using CiscoAnyconnect? Probably? I'm not sure.

**Comment by taowa** [comment]
https://share.polymtl.ca/alfresco/service/api/path/content;cm:content/workspace/SpacesStore/Company%20Home/Sites/rentree/documentLibrary/Aide-m%C3%A9moire%20tutoriels%20A2020/Checklist_VPN.pdf?a=true&guest=true is poly's guide

**Comment by RignonNoel** [comment]
I started on it and saw that it's in fact [already done](https://github.com/neuropoly/intranet.neuro.polymtl.ca/commit/a5d6fd92a15732185fc0201574b202e3ad092546) by @joshuacwnewton on April 28th. 

And @joshuacwnewton did a great job 🙌 with link to official polytechnic documentation I myself used with success, so I think there is nothing more to say on the topic.
