### ISSUE TITLE
Broken link: https://intranet.neuro.polymtl.ca/software-development/contributing

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/intranet.neuro.polymtl.ca#41]
Reported on https://neuropoly.slack.com/archives/CAW9X21D5/p1644439838169029

**Comment by mguaypaq** [comment]
This was a broken link on the [SCT developer wiki](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Contributing) to:

https://intranet.neuro.polymtl.ca/software-development/contributing

which seems to currently live here instead:

https://intranet.neuro.polymtl.ca/geek-tips/contributing

In the long term, we want to move these contribution guidelines entirely to the developer wiki (see [issue 3648](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3648)), but for now the broken link is fixed.

(There were also two other instances of the broken link on the wiki: [here]() and [here](), both fixed now too.)
