### ISSUE TITLE
Add section containing recent theses files?

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/intranet.neuro.polymtl.ca#51]
I think it could be useful for people onboarding to have access to recently published theses from the lab, maybe tagged with some relevant topics that in it or the larger projects they were involved in. Any appetite for this?

**Comment by jcohenadad** [comment]
i love this idea, and i would love even more if someone could take care of it 😊

**Comment by mathieuboudreau** [comment]
> i love this idea, and i would love even more if someone could take care of it 😊

Ok great! I'll assign myself to it then. 

> .note: theses end up being published on polypublie-- however they have an embargo of 1y-- so if we want to avoid adding fat to our github repos (~50MB per thesis) we could wait for 1y and the redirect to the polypublie website--

If we do wait a year (which is fine by me), we should also keep an active list (maybe without links) as people graduate, because unless you have an up-to-date list somewhere of your past students and when they graduated, I couldn't for the life of my remember all the names of people that graduated their MSc 1-3 years ago from the lab 😅

**Comment by mathieuboudreau** [comment]
> Could you please:
> 
> * update [this link](https://intranet.neuro.polymtl.ca/bibliography/lab-theses.html) with what you've done [here](https://intranet.neuro.polymtl.ca/bibliography/lab-theses.html)
> * in [this page](https://intranet.neuro.polymtl.ca/bibliography/lab-theses.html), create a redirection to [this page](https://neuro.polymtl.ca/publications.html#theses)

Done and done, closing.
