### ISSUE TITLE
git-annex whereis returns nothing

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/intranet.neuro.polymtl.ca#74]
i've uploaded a new dataset (canproco), and at the very end, git-annex whereis returns nothing:
~~~
julien-macbook:~/data.neuro/canproco $ git annex whereis
julien-macbook:~/data.neuro/canproco $ 
~~~

**Comment by mguaypaq** [comment]
It looks like all the files in canproco are directly in the repository, instead of being handled by git-annex. So, the good news is that the files are all available (with a simple `git clone`), but the bad news is that a simple `git clone` downloads 16G of data directly.

Looking at `git log`, it seems that everything was added in the initial commit, instead of just the configuration files (`.gitattributes` and `.gitignore`), followed by a second commit with the data files (that would be handled by git-annex). Which instructions did you follow?

**Comment by jcohenadad** [comment]
> Looking at git log, it seems that everything was added in the initial commit, instead of just the configuration files (.gitattributes and .gitignore), followed by a second commit with the data files (that would be handled by git-annex). Which instructions did you follow?

I'll copy/paste the screenshots in case the page evolves with time (so as to not create confusion).

I started from this:
![image](https://user-images.githubusercontent.com/2482071/190449957-873bb2aa-4afb-4b8c-b100-cee7bc15696a.png)

So, the first step was to click on the 'recipe', which brought me here:
![image](https://user-images.githubusercontent.com/2482071/190450221-549887c6-451e-4060-89c8-8a738e00763b.png)

Given that the repos with the data was already there, I skipped:
~~~
mkdir my-new-repo
cd my-new-repo
~~~
and I did all the rest. 

But then, I realized at the end of the recipe that I should NOT have included the data, because I saw this:
![image](https://user-images.githubusercontent.com/2482071/190450575-e1e115fd-f61d-42f7-8cb6-d0d4617e478d.png)

but it was too late, so I continued.

Maybe we should add a big disclaimer saying something like: "THE FOLDER SHOULD BE EMPTY" or something like that. I'll suggest something in a PR.

> I can try to fix things, but I'll have to force-push the master branch, otherwise the 16G of data files would always be downloaded as part of the history.

Hum, I don't know if it is worth your time (given the other priorities in the lab). At some point we discussed about the possibility to drop git-annex and only rely on git (with the inconvenience of having a double-size repos). In light of the multiple confusions that happened in the lab since git-annex was introduced, maybe we can revisit this option?

**Comment by mguaypaq** [comment]
Ok, this is done, so `data.neuro.polymtl.ca:datasets/canproco` should be in a good state right now. I tested by doing:
```
$ git clone git@data.neuro.polymtl.ca:datasets/canproco
$ cd canproco
$ file=sub-cal104/ses-M0/anat/sub-cal104_ses-M0_acq-MT_MTS.nii.gz
$ git annex whereis "$file"
(merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)
whereis sub-cal104/ses-M0/anat/sub-cal104_ses-M0_acq-MT_MTS.nii.gz (2 copies) 
  	5d6b1659-18d9-4766-aad3-f7d6f97aadff -- u119414@joplin.neuro.polymtl.ca:/tmp/tmp.GVDsJDPDQr/canproco
   	9d6c1dbe-a3bb-4509-b357-1139aec886c3 -- git@data.neuro.polymtl.ca:~/repositories/datasets/canproco.git [origin]
ok
$ git annex get "$file"
get sub-cal104/ses-M0/anat/sub-cal104_ses-M0_acq-MT_MTS.nii.gz (from origin...) 
ok                                    
(recording state in git...)
$ du -sh "$file"
4.9M	sub-cal104/ses-M0/anat/sub-cal104_ses-M0_acq-MT_MTS.nii.gz
```
For your local copy of the repository, I would recommend making a new `git clone git@data.neuro.polymtl.ca:datasets/canproco` to make sure you're also in a good state.

**Comment by mguaypaq** [comment]
> At some point we discussed about the possibility to drop git-annex and only rely on git (with the inconvenience of having a double-size repos). In light of the multiple confusions that happened in the lab since git-annex was introduced, maybe we can revisit this option?

I guess that's always an option, but that's a bigger discussion than will fit in this thread!

**Comment by kousu** [comment]
A light touch that this is off topic for this repository. I'm going to close this. Please reopen in [data-management](https://github.com/neuropoly/data-management/) if needed.
