### ISSUE TITLE
Duplication of `Git & GitHub` section

### ISSUE THREAD

**Issue by valosekj** [neuropoly/intranet.neuro.polymtl.ca#86]
It seems that `Git & GitHub` are described in a very similar manner in two sections:

[MISCELLANEOUS/🤓  Geek tips/Various Software & Tools/Git & GitHub](https://intranet.neuro.polymtl.ca/geek-tips/misc/git-and-github.html#)

[MISCELLANEOUS/🤓  Geek tips/git & Github](https://intranet.neuro.polymtl.ca/geek-tips/git.html?highlight=repository#)

**Comment by jcohenadad** [comment]
Thank you for catching this @valosekj ! It seems like [this page](https://intranet.neuro.polymtl.ca/geek-tips/git.html?highlight=repository#) is more comprehensive and up-do-that, so I would get rid of the other one after making sure there is no useful bits that is lost in the process.

**Comment by valosekj** [comment]
> It seems like [this page](https://intranet.neuro.polymtl.ca/geek-tips/git.html?highlight=repository#) is more comprehensive and up-do-that, so I would get rid of the other one after making sure there is no useful bits that is lost in the process.

Thank you. Done in https://github.com/neuropoly/intranet.neuro.polymtl.ca/commit/62a0f77d7ad6f744f96b0472290d43d2d5e539a3

**Comment by jcohenadad** [comment]
thank you @valosekj !
