### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/intranet.neuro.polymtl.ca#95]
I made two small changes this morning,

https://github.com/neuropoly/intranet.neuro.polymtl.ca/commit/a478d4de0db5c762075193d1080c67a223d04def
https://github.com/neuropoly/intranet.neuro.polymtl.ca/commit/80e6c6b8bf90648d8b26542d1dc6074d4a0911e6

and both builds fail due to something that appears to be unrelated. 

Here is the GitActions log for the most recent one: https://github.com/neuropoly/intranet.neuro.polymtl.ca/actions/runs/4331076531/jobs/7562731150#step:5:175

This is the last error message:

```
Extension error (pydata_sphinx_theme):
[172](https://github.com/neuropoly/intranet.neuro.polymtl.ca/actions/runs/4331076531/jobs/7562731150#step:5:173)
Handler <function update_and_remove_templates at 0x7f1d6214c9d0> for event 'html-page-context' threw an exception (exception: sidebar-logo.html)
[173](https://github.com/neuropoly/intranet.neuro.polymtl.ca/actions/runs/4331076531/jobs/7562731150#step:5:174)
make: *** [Makefile:20: html] Error 2
[174](https://github.com/neuropoly/intranet.neuro.polymtl.ca/actions/runs/4331076531/jobs/7562731150#step:5:175)
Error: Process completed with exit code 2.
```

It seems to be complainign about a file/setting that I didn't touch. I only see "sidebar-logo.html" in the [config file](https://github.com/neuropoly/intranet.neuro.polymtl.ca/blob/80e6c6b8bf90648d8b26542d1dc6074d4a0911e6/conf.py#L65) but can't find the static file for it.

**Comment by mguaypaq** [comment]
Ok, I found the proximate cause and a quick fix. I'll push the quick fix now, and keep investigating for a better fix.

The proximate cause: the Python package `sphinx-book-theme` [published a new release this weekend (v1.0.0)](https://pypi.org/project/sphinx-book-theme/1.0.0/#history), with [breaking changes](https://sphinx-book-theme.readthedocs.io/en/stable/changelog.html#breaking-changes-to-structure-and-api), so our build script is currently broken.

This was one of the few package version differences between [a recent successful build](https://github.com/neuropoly/intranet.neuro.polymtl.ca/actions/runs/4295345219/jobs/7485621869#step:4:104) and [the current failing build](https://github.com/neuropoly/intranet.neuro.polymtl.ca/actions/runs/4331076531/jobs/7596527099#step:4:111).

The quick fix: temporarily pin `sphinx-book-theme`'s version to be less than 1.0.0.

A better fix will be to figure out what changed in the theme, why it's unhappy with our docs specifically, and update things accordingly.

**Comment by mguaypaq** [comment]
The quick fix [seems to be working](https://github.com/neuropoly/intranet.neuro.polymtl.ca/actions/runs/4348554280/jobs/7597222312), thankfully, so at least we can update the wiki again. I'll keep digging.

**Comment by mathieuboudreau** [comment]
Great! Thanks for figuring out the problem @mguaypaq !
